spring.application.name=tournament-manager



spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_db
spring.datasource.username=postgres

#??? ??????? ????? ????????? PostgreSQL.
# ???????? ???? ?????? `tournament_db`.
# ? ????? ???????? ? IDE ????????? ?????????? ?????????:`DB_PASSWORD` ?????? PostgreSQL.
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
