spring.application.name=tournament-manager

# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_db
spring.datasource.username=postgres
spring.datasource.password=228337

spring.sql.init.mode=always
